
<div class="page-title-wrapper">
    <div class="breadcrumbs">
    <ul class="items">
                    <li class="item home">
                            <a href="<?php echo $block->getBaseUrl(); ?>" title="Go to Home Page">Home</a>
                        </li>
               
                    <li class="item create-trails">
                            <strong>create trails</strong>
                        </li>
            </ul>
</div>

<div class="content-heading">
    <h2 class="title">Create Trail</h2>
	</div>
</div>
<form class="trail-register-form" action="<?php echo $this->getUrl().'trails/post/register/'; ?>" method="post" enctype="multipart/form-data">
    <fieldset class="fieldset">
               <div class="field row">
                   <div class="col-sm-8">
                       </div>
                    <div class="col-sm-4 register-btn-wrap">
                 
                 <div style="text-align:right;">
                    <input type="submit" name="submit" class="action primary" value="publish">
                    </div>
                          <div style="text-align:right;">
                    <input type="reset" name="submit" class="action primary" value="Discard" style="background:#ccc; border-color:#ccc;" >
                    </div>
                    </div>
                    
         </div>
   <div class="row field">
       <div class="col-sm-12">
                    <label class="label" for="trails_name"><span>Trails Name</span></label>
                    <div class="control">
                       <input type="text" name="trails_name" placeholder="Trails Name" required>    
                     </div>
                     </div>
                </div>
    <div class="row field">
        <div class="col-sm-4">
              <div class="field">
                    <label class="label" for="trails_start_date"><span>Start Date</span></label>
                    <div class="control date-block">
                       <input type="date" name="trails_start_date" placeholder="Start Date" required>
                       <label class="input-group-addon btn" for="testdate">
                           <span class="fa fa-calendar"></span>
                        </label> 
                     </div>
                </div>
            
        </div>
        <div class="col-sm-4">
            <div class="field">
                    <label class="label" for="trails_end_date"><span>End Date</span></label>
                   <div class="control date-block">
                        <input type="date" name="trails_end_date" placeholder="End Date" required>
                         <label class="input-group-addon btn" for="testdate">
                           <span class="fa fa-calendar"></span>
                        </label> 
                     </div>
                </div>
        </div>
        <div class="col-sm-4">
                 <div class="field">
                    <label class="label" for="trails_vehicle_name"><span>Vehicle Name</span></label>
                    <div class="control">
                        <input type="text" name="trails_vehicle_name" placeholder="Vehicle Name" required>
                     </div>
                </div>
        </div>
        
    </div>
    <div class="row field">
        <div class="col-sm-4">
                   <div class="field">
                    <label class="label" for="trails_trip_duration"><span>Duration</span></label>
                    <div class="control">
                         <input type="text" name="trails_trip_duration" placeholder="Duration" required>
                     </div>
                </div>
            </div>
        <div class="col-sm-4">
                   <div class="field">
                    <label class="label" for="trails_start_point"><span>Start Point</span></label>
                    <div class="control">
                         <input type="text" name="trails_start_point" placeholder="Start Point" required>
                     </div>
                </div>
            </div>
        <div class="col-sm-4">
                  <div class="field">
                    <label class="label" for="trails_end_point"><span>End Point</span></label>
                    <div class="control">
                         <input type="text" name="trails_end_point" placeholder="End Point" required>
                     </div>
                </div>
            </div>
    </div>
    <div class="field row">
          <div class="col-sm-12">
                <div class="field">
                    <label class="label" for="trails_describing"><span>Description</span></label>
                    <div class="control">
                        <textarea name="trails_describing" rows="10" placeholder="Start describing your trail here..." required  id="short_description"> </textarea>
                      
                     </div>
                </div>
              </div>
      
    </div>
    <div class="field row">
          <div class="col-sm-12 upload-wrapper">
              <label class="label"><span>upload images & videos</span></label>
              <div class="uploader">
               <label class="label" for="trails_url"><span>+add photos/videos</span></label>
                   <input type="file" name="trails_url[]" placeholder="Image" multiple="multiple" id="gallery-photo-add" required>
            </div>
            <div class="gallery"></div>
            </div>
        </div>
 
    
    </fieldset>
</form>
<script>

    require([ 'jquery', 'jquery/ui'], function($){ 
   

    jQuery(function() {
    // Multiple images preview in browser
    var imagesPreview = function(input, placeToInsertImagePreview) {

        if (input.files) {
            var filesAmount = input.files.length;

            for (i = 0; i < filesAmount; i++) {
                var reader = new FileReader();

                reader.onload = function(event) {
                    jQuery($.parseHTML('<img>')).attr('src', event.target.result).appendTo(placeToInsertImagePreview);
                }

                reader.readAsDataURL(input.files[i]);
            }
        }

    };

    jQuery('#gallery-photo-add').on('change', function() {
        imagesPreview(this, 'div.gallery');
    });

});
});
</script>


<script>
    require(['jquery','tiny_mce/tiny_mce_src'], function($){
        $( document ).ready(function(){
            tinyMCE.init({
                mode : "exact",
                elements: "short_description", // id of textarea
                theme : "advanced",
                plugins : "",
                theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect",
                theme_advanced_buttons2 : "",
                theme_advanced_buttons3 : "",
                theme_advanced_buttons4 : "",
                theme_advanced_toolbar_location : "top",
                theme_advanced_toolbar_align : "left",
                // theme_advanced_path_location : "bottom",
                extended_valid_elements : "a[name|href|target|title|onclick],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name],hr[class|width|size|noshade],font[face|size|color|style],span[class|align|style]",
                theme_advanced_resize_horizontal : 'true',
                theme_advanced_resizing : 'true',
                apply_source_formatting : 'true',
                convert_urls : 'false',
                force_br_newlines : 'true',
                doctype : '',
                setup : function(ed) {
                    ed.onChange.add(function(ed, evt) {
//ed.selection.select(evt.target);
                        $('#history_comment').text(tinyMCE.activeEditor.getContent());
                    });
                }
            }); // close tinyMCE

        }); // close jquery ready
    }); // close require
</script>

<script language="javascript" type="text/javascript" src="<?php echo $block->getBaseUrl(); ?>static/adminhtml/Magento/backend/en_US/tiny_mce/tiny_mce.js"></script>

